import type { Metadata } from 'next';

import { type ReactNode } from 'react';

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

interface Properties {
  children: ReactNode;
}

export default function Layout({ children }: Readonly<Properties>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
